server {
    listen 80;
    server_name turnos.dpmake.cl;

    # Logs de Nginx
    access_log /var/log/nginx/turnos_access.log;
    error_log /var/log/nginx/turnos_error.log;

    # 1. Rutas del Frontend (Aplicación en Vite/React)
    location / {
        proxy_pass http://127.0.0.1:3010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Rutas del Backend (API en FastAPI)
    location /api/ {
        proxy_pass http://127.0.0.1:8010/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Evitar Timeouts largos en las consultas masivas o reportes
        proxy_read_timeout 90;
        proxy_connect_timeout 90;
    }

}
